[package]
name = "cli-2fa"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "2fa"
path = "src/main.rs"

[dependencies]
data-encoding = "2.3.3"
hmac = "0.12.1"
sha1 = "0.10.5"

[dev-dependencies]
chrono = "0.4.23"
